[core]
editor = code --wait
quotepath = false
commentChar = ";"

[alias]
# show option alias
branches = branch -a
derived-branches = "!git rev-parse --abbrev-ref HEAD | git branch --contains "
rename-branch = branch -m
remotes = remote -v
log-tree = log --graph --abbrev-commit --date=short --pretty=format:'%C(green)[%cd] %C(cyan)<%an> %C(red)%h%C(yellow)%d %C(reset)%s '
time-line = log --graph -20 --branches --remotes --tags --format=format:'%C(cyan)<%cN> %C(red)%h %C(reset)%<(75,trunc)%s %C(green)(%cr) %C(yellow)%d' --date-order
detail = status -uall
summary = status -s -u
# work option alias
stashes = stash list
stage = add
unstage = reset HEAD
discard = checkout
purify = clean -df
# commit = commit
uncommit = reset --mixed HEAD~
staged-diff = diff --cached

[fetch]
prune=true

[pull]
ff = only

[push]
default = simple

[merge]
ff = false

[diff]
algorithm = patience
compactionHeuristic = true
indentHeuristic = true

[pager]
log = delta
show = delta
diff = delta

[interactive]
diffFilter = delta --color-only

[delta]
navigate = true
line-numbers = true
syntax-theme = "Monokai Extended"
side-by-side = false
keep-plus-minus-markers = true
plus-style = "syntax #012800"
minus-style = "syntax #340001"
zero-style = "normal"
light = false
